<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import * as echarts from "echarts";
import type { GatewayProtectionOverview } from "../api";
const props = defineProps<{ data: GatewayProtectionOverview }>();
const trendRoot = ref<HTMLDivElement>(); const dimensionsRoot = ref<HTMLDivElement>(); let trendChart: echarts.ECharts | undefined; let dimensionChart: echarts.ECharts | undefined; let observer: ResizeObserver | undefined;
function draw() { if (!trendChart || !dimensionChart) return; trendChart.setOption({ animationDuration: 360, tooltip: { trigger: "axis" }, legend: { data: ["请求", "RPM/TPM 拒绝", "并发拒绝", "其他失败"] }, grid: { top: 42, left: 20, right: 20, bottom: 30, containLabel: true }, xAxis: { type: "category", boundaryGap: false, data: props.data.trends.map(item => item.bucket.slice(5)) }, yAxis: { type: "value" }, series: [{ name: "请求", type: "line", smooth: true, showSymbol: false, data: props.data.trends.map(item => item.requests), lineStyle: { color: "#176eac", width: 3 } }, { name: "RPM/TPM 拒绝", type: "line", smooth: true, showSymbol: false, data: props.data.trends.map(item => item.rateLimited), lineStyle: { color: "#c98528", width: 2 } }, { name: "并发拒绝", type: "line", smooth: true, showSymbol: false, data: props.data.trends.map(item => item.concurrencyLimited), lineStyle: { color: "#c95d4b", width: 2 } }, { name: "其他失败", type: "line", smooth: true, showSymbol: false, data: props.data.trends.map(item => item.otherFailures), lineStyle: { color: "#77889a", width: 2 } }] }, true); dimensionChart.setOption({ animationDuration: 360, tooltip: { trigger: "axis" }, grid: { top: 12, left: 12, right: 20, bottom: 28, containLabel: true }, xAxis: { type: "value" }, yAxis: { type: "category", data: props.data.limitDimensions.map(item => item.dimension).reverse(), axisLabel: { fontSize: 11 } }, series: [{ type: "bar", data: props.data.limitDimensions.map(item => item.count).reverse(), barMaxWidth: 22, itemStyle: { color: "#c98528", borderRadius: [0, 5, 5, 0] } }] }, true); }
onMounted(async () => { await nextTick(); if (trendRoot.value) trendChart = echarts.init(trendRoot.value); if (dimensionsRoot.value) dimensionChart = echarts.init(dimensionsRoot.value); observer = new ResizeObserver(() => { trendChart?.resize(); dimensionChart?.resize(); }); if (trendRoot.value) observer.observe(trendRoot.value); if (dimensionsRoot.value) observer.observe(dimensionsRoot.value); draw(); }); watch(() => props.data, draw, { deep: true }); onBeforeUnmount(() => { observer?.disconnect(); trendChart?.dispose(); dimensionChart?.dispose(); });
</script>
<template><section class="dashboard-chart-grid protection-chart-grid"><article class="surface dashboard-chart"><div class="section-title"><div><p class="eyebrow">Protection trend</p><h2>请求与拒绝趋势</h2></div><span class="muted">{{ data.range === '24h' ? '按小时' : '按日' }}</span></div><div ref="trendRoot" class="dashboard-chart-canvas" /></article><article class="surface dashboard-chart"><div class="section-title"><div><p class="eyebrow">Hit dimensions</p><h2>保护命中维度</h2></div></div><div ref="dimensionsRoot" class="dashboard-chart-canvas" /></article></section></template>
