<script setup lang="ts">
import { onMounted, reactive, ref, watch } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { api, type ApplicationItem, type TeamMemberItem, type TeamSummary, type VirtualApiKeyItem } from "../api";

const props = defineProps<{ defaultTeamId?: number | null; defaultMemberId?: number | null; ownerMemberId?: number | null }>();
const keys = ref<VirtualApiKeyItem[]>([]); const total = ref(0); const teams = ref<TeamSummary[]>([]); const members = ref<TeamMemberItem[]>([]); const apps = ref<ApplicationItem[]>([]); const loading = ref(false);
const filters = reactive({ keyword: "", teamId: undefined as number | undefined, applicationId: undefined as number | undefined, memberId: undefined as number | undefined, enabled: "", page: 0, size: 10 });
async function load(reset = false) { if (reset) filters.page = 0; loading.value = true; try { const result = await api.keys({ ...filters, enabled: filters.enabled || null }); keys.value = result.items; total.value = result.total; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "Key 列表加载失败"); } finally { loading.value = false; } }
async function loadTeams() { const result = await api.teams({ page: 0, size: 100 }); teams.value = result.items; }
async function loadFilterScope(teamId?: number) { filters.applicationId = undefined; filters.memberId = props.defaultMemberId ?? undefined; members.value = []; apps.value = []; if (!teamId) return; const [memberData, appData] = await Promise.all([api.members(teamId), api.applications(teamId)]); members.value = memberData.items; apps.value = appData.items; }
function applyIdentityScope() { filters.teamId = props.defaultTeamId ?? undefined; filters.memberId = props.defaultMemberId ?? undefined; filters.applicationId = undefined; filters.page = 0; }
function clear() { Object.assign(filters, { keyword: "", teamId: props.defaultTeamId ?? undefined, applicationId: undefined, memberId: props.defaultMemberId ?? undefined, enabled: "", page: 0 }); void load(); }
async function disable(key: VirtualApiKeyItem) { try { await ElMessageBox.confirm(`停用 ${key.name} 后，该成员应用的请求会立即被拒绝。`, "确认停用系统 Key", { type: "warning", confirmButtonText: "停用", cancelButtonText: "取消" }); await api.disableKey(key.keyId); ElMessage.success("Key 已停用"); await load(); } catch (error) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "停用失败"); } }
async function rotate(key: VirtualApiKeyItem) { if (!props.ownerMemberId || !key.ownerMemberId) return; try { await ElMessageBox.confirm(`轮换后 ${key.name} 将立即失效，新 Key 明文只展示一次。`, "确认轮换系统 Key", { type: "warning" }); const result = await api.rotateMemberKey(key.teamId, key.ownerMemberId, key.applicationId, props.ownerMemberId); await ElMessageBox.alert(`<p>请立即安全交付新 Key，关闭后不可恢复。</p><code>${result.apiKey}</code>`, "新 Key 已生成", { dangerouslyUseHTMLString: true, confirmButtonText: "我已记录" }); await load(); } catch (error) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "轮换失败"); } }
watch(() => filters.teamId, value => { void loadFilterScope(value); });
watch([() => props.defaultTeamId, () => props.defaultMemberId], () => { applyIdentityScope(); void load(); });
onMounted(async () => { applyIdentityScope(); await Promise.all([loadTeams(), load()]); });
</script>

<template>
  <section class="page-stack" v-loading="loading"><header class="page-heading"><div><p class="eyebrow">System-provisioned credentials</p><h1>虚拟 API Key</h1><p>负责人完成成员模型权限和额度划拨后，系统自动生成成员应用专属 Key；此处仅供查看、轮换、停用和审计。</p></div></header><section class="surface"><el-form inline class="search-bar" @submit.prevent="load(true)"><el-input v-model="filters.keyword" placeholder="名称或 Key 前缀" clearable/><el-select v-model="filters.teamId" placeholder="团队" clearable><el-option v-for="team in teams" :key="team.teamId" :label="team.name" :value="team.teamId"/></el-select><el-select v-model="filters.applicationId" placeholder="应用" clearable><el-option v-for="app in apps" :key="app.applicationId" :label="app.name" :value="app.applicationId"/></el-select><el-select v-model="filters.memberId" placeholder="成员" clearable><el-option v-for="member in members" :key="member.memberId" :label="member.name" :value="member.memberId"/></el-select><el-select v-model="filters.enabled" placeholder="状态" clearable><el-option label="启用" value="true"/><el-option label="已停用" value="false"/></el-select><el-button type="primary" native-type="submit">搜索</el-button><el-button @click="clear">重置</el-button></el-form><el-table :data="keys"><el-table-column prop="name" label="系统 Key" min-width="160"/><el-table-column prop="keyPrefix" label="前缀" min-width="150"/><el-table-column prop="teamName" label="团队"/><el-table-column prop="applicationName" label="应用"/><el-table-column prop="ownerMemberName" label="成员"/><el-table-column label="有效模型" min-width="160"><template #default="scope">{{ scope.row.allowedModels.join('，') || '未授权' }}</template></el-table-column><el-table-column label="状态" width="95"><template #default="scope"><el-tag :type="scope.row.enabled ? 'success' : 'info'">{{ scope.row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="125"><template #default="scope"><el-button v-if="props.ownerMemberId && scope.row.enabled" text type="primary" @click="rotate(scope.row)">轮换</el-button><el-button v-if="scope.row.enabled" type="danger" text @click="disable(scope.row)">停用</el-button></template></el-table-column></el-table><el-pagination class="table-pagination" background layout="total, prev, pager, next" :total="total" :page-size="filters.size" :current-page="filters.page + 1" @current-change="page => { filters.page = page - 1; load(); }"/></section></section>
</template>
