<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage } from "element-plus";
import { api, type TeamEntitlement } from "../api";
const items=ref<TeamEntitlement[]>([]), selected=ref<TeamEntitlement|null>(null), dialog=ref(false), loading=ref(false); const form=reactive({grantedModelNames:[] as string[],grantedTokens:0,reviewerNote:""});
async function load(){loading.value=true;try{items.value=(await api.entitlementRequests()).items}catch(e){ElMessage.error(e instanceof Error?e.message:"申请加载失败")}finally{loading.value=false}}
function review(item:TeamEntitlement){selected.value=item;form.grantedModelNames=[...item.modelNames];form.grantedTokens=item.requestedTokens;form.reviewerNote="";dialog.value=true}
async function submit(decision:"APPROVE"|"REJECT"){if(!selected.value)return;try{await api.reviewTeamEntitlement(selected.value.requestId,{decision,...form});dialog.value=false;await load();ElMessage.success(decision==="APPROVE"?"已批准":"已驳回")}catch(e){ElMessage.error(e instanceof Error?e.message:"处理失败")}}
onMounted(load);
</script>
<template><section class="page-stack" v-loading="loading"><header class="page-heading"><div><p class="eyebrow">Entitlement queue</p><h1>授权申请</h1><p>集中处理团队负责人提交的模型权限与额度申请。</p></div></header><section class="surface"><el-table :data="items"><el-table-column prop="teamId" label="团队 ID"/><el-table-column prop="purpose" label="用途"/><el-table-column label="申请模型"><template #default="s">{{s.row.modelNames.join('，')}}</template></el-table-column><el-table-column prop="requestedTokens" label="申请额度"/><el-table-column label="操作"><template #default="s"><el-button text type="primary" @click="review(s.row)">处理</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" title="处理申请" width="520px"><el-form label-position="top"><el-form-item label="实际模型"><el-checkbox-group v-model="form.grantedModelNames"><el-checkbox v-for="m in selected?.modelNames" :key="m" :label="m">{{m}}</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="实际额度"><el-input-number v-model="form.grantedTokens" :min="1"/></el-form-item><el-form-item label="说明"><el-input v-model="form.reviewerNote"/></el-form-item></el-form><template #footer><el-button @click="submit('REJECT')">驳回</el-button><el-button type="primary" @click="submit('APPROVE')">批准</el-button></template></el-dialog></section></template>
