<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { api, type PlatformUser } from "../api";

const users = ref<PlatformUser[]>([]); const loading = ref(false); const dialog = ref(false); const editing = ref<PlatformUser | null>(null); const developmentCredentials = ref(false);
const form = reactive({ name: "", email: "", initialPassword: "", enabled: true });
async function load() { loading.value = true; try { users.value = (await api.users()).items; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "用户列表加载失败"); } finally { loading.value = false; } }
function open(user?: PlatformUser) { editing.value = user ?? null; Object.assign(form, user ? { name: user.name, email: user.email, initialPassword: "", enabled: user.enabled } : { name: "", email: "", initialPassword: "", enabled: true }); dialog.value = true; }
async function save() { try { const saved = editing.value ? await api.updateUser(editing.value.userId, { name: form.name, email: form.email, enabled: form.enabled }) : await api.createUser(form); dialog.value = false; await load(); ElMessage.success(developmentCredentials.value && !editing.value ? `用户已保存。登录账号：${saved.email}；初始密码：123` : "用户已保存"); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保存失败"); } }
async function remove(user: PlatformUser) { try { await ElMessageBox.confirm(`删除 ${user.name} 会同时清理其成员关系、虚拟 Key、用量和额度数据，且不可恢复。`, "确认删除用户", { type: "warning" }); await api.deleteUser(user.userId); await load(); ElMessage.success("用户已删除"); } catch (error) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "删除失败"); } }
onMounted(async () => { try { developmentCredentials.value = (await api.developmentCredentials()).enabled; } catch { developmentCredentials.value = false; } await load(); });
</script>

<template>
  <section class="page-stack" v-loading="loading"><header class="page-heading"><div><p class="eyebrow">Platform user directory</p><h1>用户管理</h1><p>平台管理员维护全局用户。团队负责人从未分配用户中添加成员；负责人归属在团队工作台中设置。</p></div><el-button type="primary" @click="open()">新增用户</el-button></header><section class="surface"><el-table :data="users"><el-table-column prop="name" label="用户"/><el-table-column prop="email" :label="developmentCredentials ? '登录账号' : '邮箱'" min-width="220"/><el-table-column prop="teamName" label="所属团队"><template #default="scope">{{ scope.row.teamName || '未分配' }}</template></el-table-column><el-table-column prop="role" label="团队角色"><template #default="scope">{{ scope.row.role === 'OWNER' ? '团队负责人' : scope.row.role === 'MEMBER' ? '开发成员' : '-' }}</template></el-table-column><el-table-column label="状态"><template #default="scope"><el-tag :type="scope.row.enabled ? 'success' : 'info'">{{ scope.row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="scope"><el-button text @click="open(scope.row)">编辑</el-button><el-button text type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="editing ? '编辑用户' : '新增用户'" width="520px"><el-form label-position="top"><el-form-item label="姓名"><el-input v-model="form.name"/></el-form-item><template v-if="!developmentCredentials"><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item v-if="!editing" label="初始密码"><el-input v-model="form.initialPassword" type="password" show-password/></el-form-item></template><p v-else-if="!editing" class="form-hint">保存后将按姓名生成登录账号，初始密码统一为 123。</p><el-switch v-model="form.enabled" active-text="启用用户" inactive-text="停用用户"/></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :disabled="!form.name || (!developmentCredentials && (!form.email || (!editing && form.initialPassword.length < 12)))" @click="save">保存</el-button></template></el-dialog></section>
</template>
