<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { api, type PlatformUser, type TeamSummary } from "../api";

const users = ref<PlatformUser[]>([]); const teams = ref<TeamSummary[]>([]); const loading = ref(false); const dialog = ref(false); const editing = ref<PlatformUser | null>(null);
const form = reactive({ name: "", email: "", enabled: true, teamId: undefined as number | undefined, role: "MEMBER" });
async function load() { loading.value = true; try { const [userData, teamData] = await Promise.all([api.users(), api.teams({ page: 0, size: 100 })]); users.value = userData.items; teams.value = teamData.items; } catch (error) { ElMessage.error(error instanceof Error ? error.message : "用户列表加载失败"); } finally { loading.value = false; } }
function open(user?: PlatformUser) { editing.value = user ?? null; Object.assign(form, user ? { name: user.name, email: user.email, enabled: user.enabled, teamId: user.teamId ?? undefined, role: user.role ?? "MEMBER" } : { name: "", email: "", enabled: true, teamId: undefined, role: "MEMBER" }); dialog.value = true; }
async function save() { try { const user = editing.value ? await api.updateUser(editing.value.userId, { name: form.name, email: form.email, enabled: form.enabled }) : await api.createUser({ name: form.name, email: form.email, enabled: form.enabled }); if (form.teamId) await api.assignUserMembership(user.userId, { teamId: form.teamId, role: form.role }); dialog.value = false; await load(); ElMessage.success("用户已保存"); } catch (error) { ElMessage.error(error instanceof Error ? error.message : "保存失败"); } }
async function remove(user: PlatformUser) { try { await ElMessageBox.confirm(`删除 ${user.name} 前，系统会检查团队、Key 和审计引用。`, "确认删除用户", { type: "warning" }); await api.deleteUser(user.userId); await load(); ElMessage.success("用户已删除"); } catch (error) { if (error !== "cancel" && error !== "close") ElMessage.error(error instanceof Error ? error.message : "删除失败"); } }
onMounted(load);
</script>
<template><section class="page-stack" v-loading="loading"><header class="page-heading"><div><p class="eyebrow">Platform user directory</p><h1>用户管理</h1><p>用户不需要登录；其团队与角色用于开发期工作台切换和资源范围筛选。</p></div><el-button type="primary" @click="open()">新增用户</el-button></header><section class="surface"><el-table :data="users"><el-table-column prop="name" label="用户"/><el-table-column prop="email" label="邮箱" min-width="220"/><el-table-column prop="teamName" label="所属团队"><template #default="scope">{{ scope.row.teamName || '未分配' }}</template></el-table-column><el-table-column prop="role" label="团队角色"><template #default="scope">{{ scope.row.role === 'OWNER' ? '团队负责人' : scope.row.role === 'MEMBER' ? '开发成员' : '-' }}</template></el-table-column><el-table-column label="状态"><template #default="scope"><el-tag :type="scope.row.enabled ? 'success' : 'info'">{{ scope.row.enabled ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="140"><template #default="scope"><el-button text @click="open(scope.row)">编辑</el-button><el-button text type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table></section><el-dialog v-model="dialog" :title="editing ? '编辑用户' : '新增用户'" width="520px"><el-form label-position="top"><el-form-item label="姓名"><el-input v-model="form.name"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="所属团队"><el-select v-model="form.teamId" clearable placeholder="可稍后分配"><el-option v-for="team in teams" :key="team.teamId" :label="team.name" :value="team.teamId"/></el-select></el-form-item><el-form-item label="团队角色"><el-select v-model="form.role" :disabled="!form.teamId"><el-option label="开发成员" value="MEMBER"/><el-option label="团队负责人（将转交现有负责人）" value="OWNER"/></el-select></el-form-item><el-switch v-model="form.enabled" active-text="启用用户" inactive-text="停用用户"/></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :disabled="!form.name || !form.email" @click="save">保存</el-button></template></el-dialog></section></template>
